/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AccommodationIndexRouteImport } from './routes/accommodation/index'
import { Route as DashboardPeakDateRouteImport } from './routes/dashboard/peakDate'
import { Route as DashboardAccommodationListRouteImport } from './routes/dashboard/accommodation-list'
import { Route as DashboardAccommodationFeaturesRouteImport } from './routes/dashboard/accommodation-features'
import { Route as DashboardAccommodationBedsRouteImport } from './routes/dashboard/accommodation-beds'
import { Route as DashboardAccommodationAddRouteImport } from './routes/dashboard/accommodation-add'
import { Route as AdminPanelAddAccommodationRouteImport } from './routes/admin-panel.add-accommodation'
import { Route as AccommodationAddAccommodationRouteImport } from './routes/accommodation/add-accommodation'
import { Route as AccommodationAccommodationDetailsRouteImport } from './routes/accommodation/accommodation-details'
import { Route as AccommodationRoomidRouteImport } from './routes/accommodation/$roomid'
import { Route as AccommodationIdRouteImport } from './routes/accommodation/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AccommodationIndexRoute = AccommodationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccommodationRoute,
} as any)
const DashboardPeakDateRoute = DashboardPeakDateRouteImport.update({
  id: '/peakDate',
  path: '/peakDate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccommodationListRoute =
  DashboardAccommodationListRouteImport.update({
    id: '/accommodation-list',
    path: '/accommodation-list',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccommodationFeaturesRoute =
  DashboardAccommodationFeaturesRouteImport.update({
    id: '/accommodation-features',
    path: '/accommodation-features',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccommodationBedsRoute =
  DashboardAccommodationBedsRouteImport.update({
    id: '/accommodation-beds',
    path: '/accommodation-beds',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccommodationAddRoute =
  DashboardAccommodationAddRouteImport.update({
    id: '/accommodation-add',
    path: '/accommodation-add',
    getParentRoute: () => DashboardRoute,
  } as any)
const AdminPanelAddAccommodationRoute =
  AdminPanelAddAccommodationRouteImport.update({
    id: '/admin-panel/add-accommodation',
    path: '/admin-panel/add-accommodation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccommodationAddAccommodationRoute =
  AccommodationAddAccommodationRouteImport.update({
    id: '/add-accommodation',
    path: '/add-accommodation',
    getParentRoute: () => AccommodationRoute,
  } as any)
const AccommodationAccommodationDetailsRoute =
  AccommodationAccommodationDetailsRouteImport.update({
    id: '/accommodation-details',
    path: '/accommodation-details',
    getParentRoute: () => AccommodationRoute,
  } as any)
const AccommodationRoomidRoute = AccommodationRoomidRouteImport.update({
  id: '/$roomid',
  path: '/$roomid',
  getParentRoute: () => AccommodationRoute,
} as any)
const AccommodationIdRoute = AccommodationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccommodationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/$roomid': typeof AccommodationRoomidRoute
  '/accommodation/accommodation-details': typeof AccommodationAccommodationDetailsRoute
  '/accommodation/add-accommodation': typeof AccommodationAddAccommodationRoute
  '/admin-panel/add-accommodation': typeof AdminPanelAddAccommodationRoute
  '/dashboard/accommodation-add': typeof DashboardAccommodationAddRoute
  '/dashboard/accommodation-beds': typeof DashboardAccommodationBedsRoute
  '/dashboard/accommodation-features': typeof DashboardAccommodationFeaturesRoute
  '/dashboard/accommodation-list': typeof DashboardAccommodationListRoute
  '/dashboard/peakDate': typeof DashboardPeakDateRoute
  '/accommodation/': typeof AccommodationIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/$roomid': typeof AccommodationRoomidRoute
  '/accommodation/accommodation-details': typeof AccommodationAccommodationDetailsRoute
  '/accommodation/add-accommodation': typeof AccommodationAddAccommodationRoute
  '/admin-panel/add-accommodation': typeof AdminPanelAddAccommodationRoute
  '/dashboard/accommodation-add': typeof DashboardAccommodationAddRoute
  '/dashboard/accommodation-beds': typeof DashboardAccommodationBedsRoute
  '/dashboard/accommodation-features': typeof DashboardAccommodationFeaturesRoute
  '/dashboard/accommodation-list': typeof DashboardAccommodationListRoute
  '/dashboard/peakDate': typeof DashboardPeakDateRoute
  '/accommodation': typeof AccommodationIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/$roomid': typeof AccommodationRoomidRoute
  '/accommodation/accommodation-details': typeof AccommodationAccommodationDetailsRoute
  '/accommodation/add-accommodation': typeof AccommodationAddAccommodationRoute
  '/admin-panel/add-accommodation': typeof AdminPanelAddAccommodationRoute
  '/dashboard/accommodation-add': typeof DashboardAccommodationAddRoute
  '/dashboard/accommodation-beds': typeof DashboardAccommodationBedsRoute
  '/dashboard/accommodation-features': typeof DashboardAccommodationFeaturesRoute
  '/dashboard/accommodation-list': typeof DashboardAccommodationListRoute
  '/dashboard/peakDate': typeof DashboardPeakDateRoute
  '/accommodation/': typeof AccommodationIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodation'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/$roomid'
    | '/accommodation/accommodation-details'
    | '/accommodation/add-accommodation'
    | '/admin-panel/add-accommodation'
    | '/dashboard/accommodation-add'
    | '/dashboard/accommodation-beds'
    | '/dashboard/accommodation-features'
    | '/dashboard/accommodation-list'
    | '/dashboard/peakDate'
    | '/accommodation/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodation/$id'
    | '/accommodation/$roomid'
    | '/accommodation/accommodation-details'
    | '/accommodation/add-accommodation'
    | '/admin-panel/add-accommodation'
    | '/dashboard/accommodation-add'
    | '/dashboard/accommodation-beds'
    | '/dashboard/accommodation-features'
    | '/dashboard/accommodation-list'
    | '/dashboard/peakDate'
    | '/accommodation'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/accommodation'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/$roomid'
    | '/accommodation/accommodation-details'
    | '/accommodation/add-accommodation'
    | '/admin-panel/add-accommodation'
    | '/dashboard/accommodation-add'
    | '/dashboard/accommodation-beds'
    | '/dashboard/accommodation-features'
    | '/dashboard/accommodation-list'
    | '/dashboard/peakDate'
    | '/accommodation/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationRoute: typeof AccommodationRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminPanelAddAccommodationRoute: typeof AdminPanelAddAccommodationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/accommodation/': {
      id: '/accommodation/'
      path: '/'
      fullPath: '/accommodation/'
      preLoaderRoute: typeof AccommodationIndexRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/dashboard/peakDate': {
      id: '/dashboard/peakDate'
      path: '/peakDate'
      fullPath: '/dashboard/peakDate'
      preLoaderRoute: typeof DashboardPeakDateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accommodation-list': {
      id: '/dashboard/accommodation-list'
      path: '/accommodation-list'
      fullPath: '/dashboard/accommodation-list'
      preLoaderRoute: typeof DashboardAccommodationListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accommodation-features': {
      id: '/dashboard/accommodation-features'
      path: '/accommodation-features'
      fullPath: '/dashboard/accommodation-features'
      preLoaderRoute: typeof DashboardAccommodationFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accommodation-beds': {
      id: '/dashboard/accommodation-beds'
      path: '/accommodation-beds'
      fullPath: '/dashboard/accommodation-beds'
      preLoaderRoute: typeof DashboardAccommodationBedsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accommodation-add': {
      id: '/dashboard/accommodation-add'
      path: '/accommodation-add'
      fullPath: '/dashboard/accommodation-add'
      preLoaderRoute: typeof DashboardAccommodationAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin-panel/add-accommodation': {
      id: '/admin-panel/add-accommodation'
      path: '/admin-panel/add-accommodation'
      fullPath: '/admin-panel/add-accommodation'
      preLoaderRoute: typeof AdminPanelAddAccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation/add-accommodation': {
      id: '/accommodation/add-accommodation'
      path: '/add-accommodation'
      fullPath: '/accommodation/add-accommodation'
      preLoaderRoute: typeof AccommodationAddAccommodationRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/accommodation-details': {
      id: '/accommodation/accommodation-details'
      path: '/accommodation-details'
      fullPath: '/accommodation/accommodation-details'
      preLoaderRoute: typeof AccommodationAccommodationDetailsRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/$roomid': {
      id: '/accommodation/$roomid'
      path: '/$roomid'
      fullPath: '/accommodation/$roomid'
      preLoaderRoute: typeof AccommodationRoomidRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/$id': {
      id: '/accommodation/$id'
      path: '/$id'
      fullPath: '/accommodation/$id'
      preLoaderRoute: typeof AccommodationIdRouteImport
      parentRoute: typeof AccommodationRoute
    }
  }
}

interface AccommodationRouteChildren {
  AccommodationIdRoute: typeof AccommodationIdRoute
  AccommodationRoomidRoute: typeof AccommodationRoomidRoute
  AccommodationAccommodationDetailsRoute: typeof AccommodationAccommodationDetailsRoute
  AccommodationAddAccommodationRoute: typeof AccommodationAddAccommodationRoute
  AccommodationIndexRoute: typeof AccommodationIndexRoute
}

const AccommodationRouteChildren: AccommodationRouteChildren = {
  AccommodationIdRoute: AccommodationIdRoute,
  AccommodationRoomidRoute: AccommodationRoomidRoute,
  AccommodationAccommodationDetailsRoute:
    AccommodationAccommodationDetailsRoute,
  AccommodationAddAccommodationRoute: AccommodationAddAccommodationRoute,
  AccommodationIndexRoute: AccommodationIndexRoute,
}

const AccommodationRouteWithChildren = AccommodationRoute._addFileChildren(
  AccommodationRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccommodationAddRoute: typeof DashboardAccommodationAddRoute
  DashboardAccommodationBedsRoute: typeof DashboardAccommodationBedsRoute
  DashboardAccommodationFeaturesRoute: typeof DashboardAccommodationFeaturesRoute
  DashboardAccommodationListRoute: typeof DashboardAccommodationListRoute
  DashboardPeakDateRoute: typeof DashboardPeakDateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccommodationAddRoute: DashboardAccommodationAddRoute,
  DashboardAccommodationBedsRoute: DashboardAccommodationBedsRoute,
  DashboardAccommodationFeaturesRoute: DashboardAccommodationFeaturesRoute,
  DashboardAccommodationListRoute: DashboardAccommodationListRoute,
  DashboardPeakDateRoute: DashboardPeakDateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationRoute: AccommodationRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AdminPanelAddAccommodationRoute: AdminPanelAddAccommodationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
