/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccommodationIndexRouteImport } from './routes/accommodation/index'
import { Route as AccommodationIdRouteRouteImport } from './routes/accommodation/$id/route'
import { Route as AccommodationIdIndexRouteImport } from './routes/accommodation/$id/index'
import { Route as AccommodationIdListRoomTypesTestRouteImport } from './routes/accommodation/$id/listRoomTypesTest'
import { Route as AccommodationIdInfoRouteImport } from './routes/accommodation/$id/info'
import { Route as AccommodationIdImagesRouteImport } from './routes/accommodation/$id/images'
import { Route as AccommodationIdFeaturesRouteImport } from './routes/accommodation/$id/features'
import { Route as AccommodationIdAddRoomTypesRouteImport } from './routes/accommodation/$id/addRoomTypes'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationIndexRoute = AccommodationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccommodationRoute,
} as any)
const AccommodationIdRouteRoute = AccommodationIdRouteRouteImport.update({
  id: '/accommodation/$id',
  path: '/accommodation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationIdIndexRoute = AccommodationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccommodationIdRouteRoute,
} as any)
const AccommodationIdListRoomTypesTestRoute =
  AccommodationIdListRoomTypesTestRouteImport.update({
    id: '/listRoomTypesTest',
    path: '/listRoomTypesTest',
    getParentRoute: () => AccommodationIdRouteRoute,
  } as any)
const AccommodationIdInfoRoute = AccommodationIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AccommodationIdRouteRoute,
} as any)
const AccommodationIdImagesRoute = AccommodationIdImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AccommodationIdRouteRoute,
} as any)
const AccommodationIdFeaturesRoute = AccommodationIdFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AccommodationIdRouteRoute,
} as any)
const AccommodationIdAddRoomTypesRoute =
  AccommodationIdAddRoomTypesRouteImport.update({
    id: '/addRoomTypes',
    path: '/addRoomTypes',
    getParentRoute: () => AccommodationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/accommodation/$id': typeof AccommodationIdRouteRouteWithChildren
  '/accommodation/': typeof AccommodationIndexRoute
  '/accommodation/$id/addRoomTypes': typeof AccommodationIdAddRoomTypesRoute
  '/accommodation/$id/features': typeof AccommodationIdFeaturesRoute
  '/accommodation/$id/images': typeof AccommodationIdImagesRoute
  '/accommodation/$id/info': typeof AccommodationIdInfoRoute
  '/accommodation/$id/listRoomTypesTest': typeof AccommodationIdListRoomTypesTestRoute
  '/accommodation/$id/': typeof AccommodationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/accommodation': typeof AccommodationIndexRoute
  '/accommodation/$id/addRoomTypes': typeof AccommodationIdAddRoomTypesRoute
  '/accommodation/$id/features': typeof AccommodationIdFeaturesRoute
  '/accommodation/$id/images': typeof AccommodationIdImagesRoute
  '/accommodation/$id/info': typeof AccommodationIdInfoRoute
  '/accommodation/$id/listRoomTypesTest': typeof AccommodationIdListRoomTypesTestRoute
  '/accommodation/$id': typeof AccommodationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/accommodation/$id': typeof AccommodationIdRouteRouteWithChildren
  '/accommodation/': typeof AccommodationIndexRoute
  '/accommodation/$id/addRoomTypes': typeof AccommodationIdAddRoomTypesRoute
  '/accommodation/$id/features': typeof AccommodationIdFeaturesRoute
  '/accommodation/$id/images': typeof AccommodationIdImagesRoute
  '/accommodation/$id/info': typeof AccommodationIdInfoRoute
  '/accommodation/$id/listRoomTypesTest': typeof AccommodationIdListRoomTypesTestRoute
  '/accommodation/$id/': typeof AccommodationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/'
    | '/accommodation/$id/addRoomTypes'
    | '/accommodation/$id/features'
    | '/accommodation/$id/images'
    | '/accommodation/$id/info'
    | '/accommodation/$id/listRoomTypesTest'
    | '/accommodation/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/accommodation'
    | '/accommodation/$id/addRoomTypes'
    | '/accommodation/$id/features'
    | '/accommodation/$id/images'
    | '/accommodation/$id/info'
    | '/accommodation/$id/listRoomTypesTest'
    | '/accommodation/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/'
    | '/accommodation/$id/addRoomTypes'
    | '/accommodation/$id/features'
    | '/accommodation/$id/images'
    | '/accommodation/$id/info'
    | '/accommodation/$id/listRoomTypesTest'
    | '/accommodation/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AccommodationIdRouteRoute: typeof AccommodationIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation/': {
      id: '/accommodation/'
      path: '/'
      fullPath: '/accommodation/'
      preLoaderRoute: typeof AccommodationIndexRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/$id': {
      id: '/accommodation/$id'
      path: '/accommodation/$id'
      fullPath: '/accommodation/$id'
      preLoaderRoute: typeof AccommodationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation/$id/': {
      id: '/accommodation/$id/'
      path: '/'
      fullPath: '/accommodation/$id/'
      preLoaderRoute: typeof AccommodationIdIndexRouteImport
      parentRoute: typeof AccommodationIdRouteRoute
    }
    '/accommodation/$id/listRoomTypesTest': {
      id: '/accommodation/$id/listRoomTypesTest'
      path: '/listRoomTypesTest'
      fullPath: '/accommodation/$id/listRoomTypesTest'
      preLoaderRoute: typeof AccommodationIdListRoomTypesTestRouteImport
      parentRoute: typeof AccommodationIdRouteRoute
    }
    '/accommodation/$id/info': {
      id: '/accommodation/$id/info'
      path: '/info'
      fullPath: '/accommodation/$id/info'
      preLoaderRoute: typeof AccommodationIdInfoRouteImport
      parentRoute: typeof AccommodationIdRouteRoute
    }
    '/accommodation/$id/images': {
      id: '/accommodation/$id/images'
      path: '/images'
      fullPath: '/accommodation/$id/images'
      preLoaderRoute: typeof AccommodationIdImagesRouteImport
      parentRoute: typeof AccommodationIdRouteRoute
    }
    '/accommodation/$id/features': {
      id: '/accommodation/$id/features'
      path: '/features'
      fullPath: '/accommodation/$id/features'
      preLoaderRoute: typeof AccommodationIdFeaturesRouteImport
      parentRoute: typeof AccommodationIdRouteRoute
    }
    '/accommodation/$id/addRoomTypes': {
      id: '/accommodation/$id/addRoomTypes'
      path: '/addRoomTypes'
      fullPath: '/accommodation/$id/addRoomTypes'
      preLoaderRoute: typeof AccommodationIdAddRoomTypesRouteImport
      parentRoute: typeof AccommodationIdRouteRoute
    }
  }
}

interface AccommodationIdRouteRouteChildren {
  AccommodationIdAddRoomTypesRoute: typeof AccommodationIdAddRoomTypesRoute
  AccommodationIdFeaturesRoute: typeof AccommodationIdFeaturesRoute
  AccommodationIdImagesRoute: typeof AccommodationIdImagesRoute
  AccommodationIdInfoRoute: typeof AccommodationIdInfoRoute
  AccommodationIdListRoomTypesTestRoute: typeof AccommodationIdListRoomTypesTestRoute
  AccommodationIdIndexRoute: typeof AccommodationIdIndexRoute
}

const AccommodationIdRouteRouteChildren: AccommodationIdRouteRouteChildren = {
  AccommodationIdAddRoomTypesRoute: AccommodationIdAddRoomTypesRoute,
  AccommodationIdFeaturesRoute: AccommodationIdFeaturesRoute,
  AccommodationIdImagesRoute: AccommodationIdImagesRoute,
  AccommodationIdInfoRoute: AccommodationIdInfoRoute,
  AccommodationIdListRoomTypesTestRoute: AccommodationIdListRoomTypesTestRoute,
  AccommodationIdIndexRoute: AccommodationIdIndexRoute,
}

const AccommodationIdRouteRouteWithChildren =
  AccommodationIdRouteRoute._addFileChildren(AccommodationIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AccommodationIdRouteRoute: AccommodationIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
