/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccommodationIndexRouteImport } from './routes/accommodation/index'
import { Route as AccommodationAddAccommodationRouteImport } from './routes/accommodation/add-accommodation'
import { Route as AccommodationAccommodationDetailsRouteImport } from './routes/accommodation/accommodation-details'
import { Route as AccommodationRoomidRouteImport } from './routes/accommodation/$roomid'
import { Route as AccommodationIdRouteImport } from './routes/accommodation/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationIndexRoute = AccommodationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccommodationRoute,
} as any)
const AccommodationAddAccommodationRoute =
  AccommodationAddAccommodationRouteImport.update({
    id: '/add-accommodation',
    path: '/add-accommodation',
    getParentRoute: () => AccommodationRoute,
  } as any)
const AccommodationAccommodationDetailsRoute =
  AccommodationAccommodationDetailsRouteImport.update({
    id: '/accommodation-details',
    path: '/accommodation-details',
    getParentRoute: () => AccommodationRoute,
  } as any)
const AccommodationRoomidRoute = AccommodationRoomidRouteImport.update({
  id: '/$roomid',
  path: '/$roomid',
  getParentRoute: () => AccommodationRoute,
} as any)
const AccommodationIdRoute = AccommodationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccommodationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/$roomid': typeof AccommodationRoomidRoute
  '/accommodation/accommodation-details': typeof AccommodationAccommodationDetailsRoute
  '/accommodation/add-accommodation': typeof AccommodationAddAccommodationRoute
  '/accommodation/': typeof AccommodationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/$roomid': typeof AccommodationRoomidRoute
  '/accommodation/accommodation-details': typeof AccommodationAccommodationDetailsRoute
  '/accommodation/add-accommodation': typeof AccommodationAddAccommodationRoute
  '/accommodation': typeof AccommodationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/$roomid': typeof AccommodationRoomidRoute
  '/accommodation/accommodation-details': typeof AccommodationAccommodationDetailsRoute
  '/accommodation/add-accommodation': typeof AccommodationAddAccommodationRoute
  '/accommodation/': typeof AccommodationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodation'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/$roomid'
    | '/accommodation/accommodation-details'
    | '/accommodation/add-accommodation'
    | '/accommodation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/$roomid'
    | '/accommodation/accommodation-details'
    | '/accommodation/add-accommodation'
    | '/accommodation'
  id:
    | '__root__'
    | '/'
    | '/accommodation'
    | '/dashboard'
    | '/accommodation/$id'
    | '/accommodation/$roomid'
    | '/accommodation/accommodation-details'
    | '/accommodation/add-accommodation'
    | '/accommodation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationRoute: typeof AccommodationRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation/': {
      id: '/accommodation/'
      path: '/'
      fullPath: '/accommodation/'
      preLoaderRoute: typeof AccommodationIndexRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/add-accommodation': {
      id: '/accommodation/add-accommodation'
      path: '/add-accommodation'
      fullPath: '/accommodation/add-accommodation'
      preLoaderRoute: typeof AccommodationAddAccommodationRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/accommodation-details': {
      id: '/accommodation/accommodation-details'
      path: '/accommodation-details'
      fullPath: '/accommodation/accommodation-details'
      preLoaderRoute: typeof AccommodationAccommodationDetailsRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/$roomid': {
      id: '/accommodation/$roomid'
      path: '/$roomid'
      fullPath: '/accommodation/$roomid'
      preLoaderRoute: typeof AccommodationRoomidRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/$id': {
      id: '/accommodation/$id'
      path: '/$id'
      fullPath: '/accommodation/$id'
      preLoaderRoute: typeof AccommodationIdRouteImport
      parentRoute: typeof AccommodationRoute
    }
  }
}

interface AccommodationRouteChildren {
  AccommodationIdRoute: typeof AccommodationIdRoute
  AccommodationRoomidRoute: typeof AccommodationRoomidRoute
  AccommodationAccommodationDetailsRoute: typeof AccommodationAccommodationDetailsRoute
  AccommodationAddAccommodationRoute: typeof AccommodationAddAccommodationRoute
  AccommodationIndexRoute: typeof AccommodationIndexRoute
}

const AccommodationRouteChildren: AccommodationRouteChildren = {
  AccommodationIdRoute: AccommodationIdRoute,
  AccommodationRoomidRoute: AccommodationRoomidRoute,
  AccommodationAccommodationDetailsRoute:
    AccommodationAccommodationDetailsRoute,
  AccommodationAddAccommodationRoute: AccommodationAddAccommodationRoute,
  AccommodationIndexRoute: AccommodationIndexRoute,
}

const AccommodationRouteWithChildren = AccommodationRoute._addFileChildren(
  AccommodationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationRoute: AccommodationRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
